{% set name = "VTP" %}
{% set version = "1.0.0" %}

package:
  name: {{name|lower}}
  version: {{version}}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  git_rev: 1.0.0

build:
  number: 0
  script: "{{ python }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python

  run:
    - python

about:
  description: 'The VTP package contains functions for processing vehicle
    telematics data and applying deterministic equations to characterize a
    the driving activity of a vehicle.'
  home: https://github.com/ajyoshizumi/VTP
  license: Apache-2.0
  license_file: LICENSE.txt